---
- name: check whether webapp is already installed
  stat: path={{app_base_directory}}
  register: p
  tags: webapp

- name: copy id_rsa
  copy: src=~/.ssh/id_rsa dest={{user}}/.ssh/ owner={{user_name}} group={{user_name}} mode=0600
  when: not (p.stat.isdir is defined and p.stat.isdir)
  tags: webapp

- name: git clone webapp
  git:
    repo={{repo}}
    dest={{app_base_directory}}
    accept_hostkey=yes
  when: not (p.stat.isdir is defined and p.stat.isdir)
  tags: webapp
