---
- name: be sure common packages are installed
  yum: name={{item}} state=installed
  with_items:
    - yum-priorities
    - libselinux-python
    - ntp
    - bind-utils
    - vim
    - wget
    - git
    - python-devel
    - python-setuptools
    - redis
  tags: common-packages

- name: be sure redis is started and autostarted
  service: name=redis state=started enabled=yes
  tags: redis
